name: healthy_lux_admin
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_storage: ^10.1.0
  firebase_database: ^8.1.0
  cloud_firestore: ^3.1.0
  fluttertoast: ^8.0.8
  simple_animations: ^4.0.1
  uuid: ^3.0.5
  image_picker: ^0.8.4+4
  file_picker: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true

  assets: 
    - images/

